### ISSUE TITLE
ruta de certificados

### ISSUE THREAD

**Issue by juanledesma** [ivanalemunioz/afip.php#10]
Buenas noches. existe la posibilidad de pasar la ruta completa de los certificados, y que esta no sea relativa a la carpeta afip_res?

estuve revisando el codigo, se que parte hay que cambiar, pero este cambio se revertirá con futuras actualizaciones?

aguardo comentarios, saludos.

**Comment by juanledesma** [comment]
buenas noches guillermo. 
te paso el codigo que utiliza y el error que me arroja.

estoy usando la api con laravel 5.6 y la instale via composer.

`$urlCert = 'homologacion_20313883516.crt';
 $urlKey =  'homologacion_20313883516.key';
$afip = new \Afip(array('CUIT' => 20XXXXXXXX6,'cert'=>$urlCert,'key'=>$urlKey));`

de esta forma funciona bien. porque tengo los certificados en la carpeta "vendor\ivanalemunioz\afip.php\src\Afip_res"

lo que quiero es sacar los certificados de esa carpeta y colocarlos por ej en public 

`$urlCert = public_path('afip').'/'.'homologacion_20313883516.crt';
        $urlKey =  public_path('afip').'/'.'homologacion_20313883516.key';

        $afip = new \Afip(array('CUIT' => 20313883516,'cert'=>$urlCert,'key'=>$urlKey));`

al hacer esto me da error ya que toma la carpeta afip_res como raíz.

se entiende lo que digo?

lo que no se es si, al modificar el codigo fuente, esta modificación se revertirá con las actualizaciones.

**Comment by ivanalemunioz** [comment]
Actualmente no se puede la rita completa, solo relativa a afip_res, por
ahora si queres que este fuera de esa carpeta podes lograrlo agregandole
“../“ para navegar hacia atras en la ruta

**Comment by juanledesma** [comment]
Gracias. Voy a probar indicas

Enviado desde Correo<https://go.microsoft.com/fwlink/?LinkId=550986> para Windows 10

________________________________
De: Ivan Muñoz <notifications@github.com>
Enviado: Saturday, August 18, 2018 11:02:45 PM
Para: ivanalemunioz/afip.php
Cc: Juan Luis Ledesma; Author
Asunto: Re: [ivanalemunioz/afip.php] ruta de certificados (#10)

Actualmente no se puede la rita completa, solo relativa a afip_res, por
ahora si queres que este fuera de esa carpeta podes lograrlo agregandole
“../“ para navegar hacia atras en la ruta
