### ISSUE TITLE
PDF

### ISSUE THREAD

**Issue by juanledesma** [ivanalemunioz/afip.php#12]
Buenos días. Saben si se cambio el tamaño mínimo de las facturas, hasta donde se es de una hoja a5. Yo uso jasper report para crear las mismas.

Se podría implementar algo que genere las facturas automáticamente, justo con la autorización.?

**Comment by guillebalmacedaonline** [comment]
Buenas, hable con una persona que trabaja en AFIP en mas es inspector. Y me dijo que no importa el formato... de todos modos la información que vale es la online. Si estas en el regimen de facturacion electronica es dificil que te pidan las facturas, ahora es posible que te pidan un reporte de sistema con los totales mensuales o anuales. Sintesis el FORMATO no importa. Eso si tiene que tener todos los datos como cualquier factura electronica. CUIT, ingreso brutos, inicio actividad, conceptos de venta, numero factura, tipo de factura, razon social de emisor y receptor con numero de documento a la vista, ETC, ETC.

**Comment by juanledesma** [comment]
Perfecto. Porque quería implementar el sistema con una impresora térmica. Con esto ya lo puedo hacer…

Es buena información la de los totales. En el sistema voy a generar un reporte que informe todos los datos y los imprima en un reporte.

Gracias.

Enviado desde Correo<https://go.microsoft.com/fwlink/?LinkId=550986> para Windows 10

________________________________
De: Balmaceda Guillermo Federico <notifications@github.com>
Enviado: Thursday, August 30, 2018 3:02:57 PM
Para: ivanalemunioz/afip.php
Cc: Juan Luis Ledesma; Author
Asunto: Re: [ivanalemunioz/afip.php] PDF (#12)


Buenas, hable con una persona que trabaja en AFIP en mas es inspector. Y me dijo que no importa el formato... de todos modos la información que vale es la online. Si estas en el regimen de facturacion electronica es dificil que te pidan las facturas, ahora es posible que te pidan un reporte de sistema con los totales mensuales o anuales. Sintesis el FORMATO no importa. Eso si tiene que tener todos los datos como cualquier factura electronica. CUIT, ingreso brutos, inicio actividad, conceptos de venta, numero factura, tipo de factura, razon social de emisor y receptor con numero de documento a la vista, ETC, ETC.

**Comment by guillebalmacedaonline** [comment]
Si juan lo haces con termica es un golaso, yo estoy implementando lo mismo por eso averigue el tema del formato... igualmente no te quedes con mi palabra, fijate algun otro contador, pero si es con la gente de afip mejor todavia.

**Comment by juanledesma** [comment]
Estoy hace dos meses averiguando. Los contadores. Algunos me dicen que el formato no importa, otros que según el régimen (no me acuerdo cual) se tiene que hacer en formato A4 o A5. Otros no tienen idea de que les hablo. Y afip no me respondió todavía. Voy a ver si me comunico por teléfono y me confirman.

Con que sistema imprimirs en la impresora fiscal? Yo estoy queriendo usar alguna librería que lo imprima de una.

Enviado desde Correo<https://go.microsoft.com/fwlink/?LinkId=550986> para Windows 10

________________________________
De: Balmaceda Guillermo Federico <notifications@github.com>
Enviado: Thursday, August 30, 2018 3:09:15 PM
Para: ivanalemunioz/afip.php
Cc: Juan Luis Ledesma; Author
Asunto: Re: [ivanalemunioz/afip.php] PDF (#12)


Si juan lo haces con termica es un golaso, yo estoy implementando lo mismo por eso averigue el tema del formato... igualmente no te quedes con mi palabra, fijate algun otro contador, pero si es con la gente de afip mejor todavia.

**Comment by ivanalemunioz** [comment]
Si tienen alguna consulta o duda pueden resolverla en el nuevo [foro de la librería](https://groups.google.com/forum/#!forum/afip-php)
