### ISSUE TITLE
"Use of undefined constant SOAP_1_2 - assumed 'SOAP_1_2' (this will throw an Error in a future version of PHP)"

### ISSUE THREAD

**Issue by juanledesma** [ivanalemunioz/afip.php#7]
Hola Ivan, estoy intentando utilizar el sdk en un proyecto con laravel, realice la instalacion via composer.
al momento de iniciar arroja la siguiente excepción.

"Use of undefined constant SOAP_1_2 - assumed 'SOAP_1_2' (this will throw an Error in a future version of PHP)"

la versión de php que utilizo es 7.2.3, lo estoy probando en un servidor local con windows 10.

el codigo que utilizo para iniciar la clase es : 

`$afip = new \Afip(array('CUIT'=>'xxxxxxxxxxx'));
 $server_status = $afip->ElectronicBilling->GetServerStatus();`

sabrás cual es el problema?
saludos.

**Comment by ivanalemunioz** [comment]
Hola Juan, tenes habilitada la extension SOAP?

**Comment by juanledesma** [comment]
Que NABO, no… ahí la habilite y me dio como respuesta:

"AppServer": "OK","DbServer": "OK","AuthServer": "OK"

Gracias por tu rápida respuesta…

Enviado desde Correo<https://go.microsoft.com/fwlink/?LinkId=550986> para Windows 10

________________________________
De: Ivan Muñoz <notifications@github.com>
Enviado: Friday, July 13, 2018 11:45:39 AM
Para: ivanalemunioz/afip.php
Cc: Juan Luis Ledesma; Author
Asunto: Re: [ivanalemunioz/afip.php] "Use of undefined constant SOAP_1_2 - assumed 'SOAP_1_2' (this will throw an Error in a future version of PHP)" (#7)


Hola Juan, tenes habilitada la extension SOAP?
