### ISSUE TITLE
No aparecio CUIT en lista de relaciones

### ISSUE THREAD

**Issue by coneman72** [ivanalemunioz/afip.php#8]
Le desarrollé a un cliente el módulo de Factura Electrónica en PHP y en mi entorno de pruebas anda perfecto (PHP 5.6 y Soap 5.6) pero cuando lo migré al cliente que tiene PHP 5.3 primero me daba un error de SOAP (no tenía instalada la extensión), la instalé y ahora me da el error

Fatal error: Uncaught exception 'Exception' with message '(600) ValidacionDeToken: No aparecio CUIT en lista de relaciones

El cuit está bien y es el mismo del certificado, así que sospecho que es algo del PHP o del Soap, no tengo forma de actualizarlos porque forman parte de un Servidor (Clearos 5.2) que tiene el Cliente. Hay forma de evitar ese error?

Muchas gracias, excelente laburazo.

**Comment by ivanalemunioz** [comment]
Y el sistema del cliente tiene arquitectura de 64bits?

**Comment by coneman72** [comment]
Entiendo yo que si, es un Intel(R) Core(TM) i3-2120 CPU @ 3.30GHz, 4 cores según Webmin, o no depende del hardware?

**Comment by ivanalemunioz** [comment]
Si el hardware lo soporta ya depende del software, en la info de php creo que debe decir que arquitectura es

**Comment by coneman72** [comment]
Si ahí miré con las instrucciones: 

<?php
 function  is64bits()
{ 
 return (PHP_INT_SIZE == 8);
}

if (is64bits() == true) echo "PHP es de 64 bits";
if (is64bits() == false) echo "PHP es de 32 bits";


y me devuelve que es de 32 bits. Tengo que reinstalarle el servidor entonces?

**Comment by ivanalemunioz** [comment]
Seguro eso te este causando problemas, deberias instalarle una version de 64bit

**Comment by coneman72** [comment]
Bueno, me pongo en campaña con el Cliente para reinstalar el Server. Muchas gracias por la info y por la buena onda. Saludos.
