### ISSUE TITLE
Problema consultar comprobante

### ISSUE THREAD

**Issue by guillebalmacedaonline** [ivanalemunioz/afip.php#9]
Hola Ivan hay un tema con el get del proximo comprobante. Me lanza el siguiente error
Fatal error</b>:  Uncaught Exception: (11002) El punto de venta no se encuentra habilitado a usar en el presente WS. Ver metodo FEParamGetPtosVenta 

seguramente es una actualizacion de afip.

**Comment by ivanalemunioz** [comment]
Justo me estaban consultando porbel mismo error que aparecio de forma
espontanea, cooncido que debe ser una actualización, lo investigo y te
aviso, si encontras la solución no dudes en compartirla

**Comment by coneman72** [comment]
A mi me pasó en un cliente (justo hoy empezó a facturar en forma electrónica) y tuvimos que dar de alta un nuevo punto de venta en la página de AFIP colocando en Sistema "RECE para aplicativo y web services" con eso funcionó sin problemas. Hasta ayer en entorno de testing no había problemas.

**Comment by ivanalemunioz** [comment]
Claro es medio raro porque antes no tenian problema con eso en modo
testing, pero hay un comunicado de que estan haciendo cambios y pruebas
asique supongo que debe de ser eso
